### ISSUE TITLE
135 - Aggregate is Invalid or Inactive

### ISSUE THREAD

**Issue by ariusxi** [vitorccsiqueira/zenvia-php#3]
Quando eu tento enviar um SMS usando a biblioteca ele me retorna o status "Detalhe: 135 - Aggregate is Invalid or Inactive", tem alguma forma de passar agrgegateId? Pelo que eu vi ele retorna isso porque eu não inclui esse parametro.

**Comment by vitorccs** [comment]
@ariusxi envie como 2o parâmetro do método "send"
https://github.com/vitorccs/zenvia-php/blob/master/src/Model/SmsFacade.php#L61

**Comment by ariusxi** [comment]
Muito obrigado, funcionou perfeitamente!
